site_name: Teachings — Web Aufträge
site_description: Aufgaben für den Webkurs
site_author: Tim Leibacher

docs_dir: web

site_url: https://tim-leibacher.github.io/Teachings/

theme:
  name: material

  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.suggest

plugins:
  - search

repo_url: https://github.com/Tim-Leibacher/Teachings

exclude:
  - "**/node_modules/**"
