site_name: Web Aufträge
site_description: Aufgaben für den Webkurs
site_author: Tim Leibacher
docs_dir: docs
site_url: https://tim-leibacher.github.io/Teachings/

theme:
  name: material
  language: de

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Zu Dunkelmodus wechseln

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Zu Hellmodus wechseln

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: de

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - tables
  - attr_list

exclude_docs: |
  ../storyboards/

repo_url: https://github.com/Tim-Leibacher/Teachings

nav:
  - HTML:
      - HTML Struktur:
          - Auftrag 1 - Dein Portfolio-Grundgerüst: 01-HTML/01-Struktur/01-Grundgeruest.md
          - Auftrag 2 - Willkommen auf deinem Portfolio: 01-HTML/01-Struktur/02-Erste-Inhalte.md
          - Auftrag 3 - Professionelle Seitenstruktur: 01-HTML/01-Struktur/03-Semantik.md
          - Auftrag 4 - Barrierefreiheit & SEO: 01-HTML/01-Struktur/04-Optional-Accessibility.md
      - HTML Text:
          - Auftrag 1 - "Über mich": 01-HTML/02-Text/01-Ueber-mich.md
          - Auftrag 2 - Wichtiges hervorheben: 01-HTML/02-Text/02-Formatierung.md
          - Auftrag 3 - Skills & Interessen: 01-HTML/02-Text/03-Listen.md
          - Auftrag 4 - Typografie & Textgestaltung: 01-HTML/02-Text/04-Optional-Typografie.md
      - HTML Links & Bilder:
          - Auftrag 1 - Navigation: 01-HTML/03-LinksBilder/01-Navigation.md
          - Auftrag 2 - Bilder einbinden: 01-HTML/03-LinksBilder/02-Bilder.md
          - Auftrag 3 - Projekt-Galerie: 01-HTML/03-LinksBilder/03-Projekt-Galerie.md
          - Auftrag 4 - Performance & Bildoptimierung: 01-HTML/03-LinksBilder/04-Optional-Performance.md
      - HTML Formulare:
          - Auftrag 1 - Kontaktformular: 01-HTML/04-Formulare/01-Kontaktformular.md
          - Auftrag 2 - Anmeldeformular: 01-HTML/04-Formulare/02-Anmeldeformular.md
          - Auftrag 3 - Feedbackformular: 01-HTML/04-Formulare/03-Feedback-Formular.md
          - Auftrag 4 - Fortgeschritten: 01-HTML/04-Formulare/04-Optional-Fortgeschritten.md
  - CSS:
      - CSS Einbindung:
          - Auftrag 1 - Erste Styles: 02-CSS/01-Einbindung/01-Erste-Styles.md
          - Auftrag 2 - Head: 02-CSS/01-Einbindung/02-Head.md
          - Auftrag 3 - Professionell: 02-CSS/01-Einbindung/03-Professionell.md
          - Auftrag 4 - Struktur: 02-CSS/01-Einbindung/04-Struktur.md
      - Selektoren:
          - Auftrag 1 - Klassenselektor: 02-CSS/02-Selektoren/01-Element-Klassen-Selektoren.md
          - Auftrag 2 - Box Modell: 02-CSS/02-Selektoren/02-Box-Modell-Abstaende.md
          - Auftrag 3 - Farben & Schriften: 02-CSS/02-Selektoren/03-Farben-Schriften-Selektoren.md
      - BoxModell:
          - Auftrag 1 - Grundlagen: 02-CSS/03-BoxModell/01-Grundlagen.md
          - Auftrag 2 - BoxSizing: 02-CSS/03-BoxModell/02-BoxSizing-Display.md
          - Auftrag 3 - Margin: 02-CSS/03-BoxModell/03-MarginCollapsing-Layout.md
          - Auftrag 4 - Fortgeschritten: 02-CSS/03-BoxModell/04-Optional-Fortgeschritten.md
      - Responsive Design:
          - Auftrag 1 - Mobile Basis: 02-CSS/04-Responsive/01-Mobile-Basis.md
          - Auftrag 2 - Tablet: 02-CSS/04-Responsive/02-Tablet-Ansicht.md
          - Auftrag 3 - Desktop Ansicht: 02-CSS/04-Responsive/03-Desktop-Ansicht.md
          - Auftrag 4 - Fortgeschritten: 02-CSS/04-Responsive/04-Optional-Advanced.md
  - Javascript:
      - JS Basics:
          - Auftrag 1 - Erste Ausgaben: 03-JAVASCRIPT/01-Basics/01-Erste-Ausgaben.md
          - Auftrag 2 - Externe Datei: 03-JAVASCRIPT/01-Basics/02-Externe-Datei.md
          - Auftrag 3 - DOM Manipulation: 03-JAVASCRIPT/01-Basics/03-DOM-Manipulation.md
          - Auftrag 4 - Skill System: 03-JAVASCRIPT/01-Basics/04-Optional-Skill-System.md
      - JS Daten:
          - Auftrag 1 - Persönliche Daten: 03-JAVASCRIPT/02-Daten/01-Persoenliche-Daten.md
          - Auftrag 2 - Intelligente Begrüssung: 03-JAVASCRIPT/02-Daten/02-Intelligente-Begruessung.md
          - Auftrag 3 - Skills Liste: 03-JAVASCRIPT/02-Daten/03-Skills-Liste.md
          - Auftrag 4 - Dashboard: 03-JAVASCRIPT/02-Daten/04-Optional-Dashboard.md
      - JS DOM:
          - Auftrag 1 - DOM Manipulation: 03-JAVASCRIPT/03-Dom/01-DOM-Manipulation.md
          - Auftrag 2 - Interaktives Profil: 03-JAVASCRIPT/03-Dom/02-Interaktives-Profil.md
          - Auftrag 3 - Projekt Galerie: 03-JAVASCRIPT/03-Dom/03-Projekt-Galerie.md
          - Auftrag 4 - Theme Switcher: 03-JAVASCRIPT/03-Dom/4-Optional-Theme-Switcher.md
      - JS Events & Fetch:
          - Auftrag 1 - Interaktive Portfolio Sektion: 03-JAVASCRIPT/04-Misc/01-Interaktive-Portfolio-Sektion.md
          - Auftrag 2 - API Integration: 03-JAVASCRIPT/04-Misc/02-API-Integration-Fetch-Async.md
          - Auftrag 3 - GitHub User Suche: 03-JAVASCRIPT/04-Misc/03-GitHub-User-Suche.md
          - Auftrag 4 - API Dashboard: 03-JAVASCRIPT/04-Misc/04-Optional-API-Dashboard.md
  - Diverses:
      - OWASP Top 10:
          - Auftrag 1 - OWASP Einführun: 04-MISC/01-OWASP/01-OWASP-Kennenlernen.md
          - Auftrag 2 - Sicherheitslücken: 04-MISC/01-OWASP/02-Sicherheitsluecken-Beheben.md
          - Auftrag 3 - Portfolio: 04-MISC/01-OWASP/03-Portfolio-Sicherheits-Checkliste.md
          - Auftrag 4 - Optional: 04-MISC/01-OWASP/04-Optionale-Security-Headers.md
      - JSON:
          - Auftrag 1 - Portfolio Daten: 04-MISC/01-JSON/01-JSON-Portfolio-Daten.md
          - Auftrag 2 - Validierung: 04-MISC/02-JSON/02-JSON-Validieren-Debuggen.md
          - Auftrag 3 - API Daten: 04-MISC/02-JSON/03-JSON-API-Daten.md
          - Auftrag 4 - Optional: 04-MISC/02-JSON/04-Optional-JSON-Konfigurationssystem.md
